### ISSUE TITLE
Chromium Switches: Last update in August 2020

### ISSUE THREAD

**Issue by The-Compiler** [beverloo/peter.sh#49]
Thanks a lot for your  [List of Chromium Command Line Switches](https://peter.sh/experiments/chromium-command-line-switches/) - as the main developer of [qutebrowser](https://www.qutebrowser.org/), it's a very useful reference!

Unfortunately, it looks like the page says:

>  Last automated update occurred on **2020-08-12**.

Yet says:

> Based on top-of-tree Chromium code, updated daily

So I assume something broke at some point?

**Comment by confor** [comment]
Maybe it's because Chromium renamed their `master` branch to `main`?

CommandLineFlags.php should have that line renamed

https://github.com/beverloo/peter.sh/blob/c07eab397d6ce6184359554b62cae17656d2c032/services/services/command-line-flags/CommandLineFlags.php#L382

I have no idea how to test if this is the source of the lack of updates.

**Comment by confor** [comment]
We have an update 😄

> Unfortunately, it looks like the page says:
> 
> > Last automated update occurred on **2020-08-12**.

It now says "Last automated update occurred on unknown." so there was an update at some point.

**Comment by beverloo** [comment]
The list is updating again, thank you for being patient :)

Previous caveats still apply:

  * Updates will be ran weekly, at 3:35am on Monday morning, Europe/Amsterdam time,
  * `base::Feature` options are not included, as they're not command line flags,
  * Macro magic is not expanded (e.g. #45).
